use_frameworks!

target 'WTCoreGraphicsExtensions_Tests' do
    pod 'WTCoreGraphicsExtensions', :path => '../'
    pod 'WTBinaryFloatingPointExtensions'
    pod 'WTUIColorExtensions'
    pod 'WTBoolExtensions'
end

